version: '2'
volumes:
  couchdb_data: {}
services:

# Build Couchdb Service
  
  couchdb:
    env_file:
     - variables.env
    build: ./iihs_curation_couch  
    ports:
     - "5984:5984"
    volumes:
     - "couchdb_data:/usr/local/var/lib/couchdb"

#Build Feedparser Service

  feedparser:
    env_file:
     - variables.env
    build: ./iihs_curation_feedparser
    depends_on:
     - couchdb  
    ports:
     - "3500:3500"

# Build the container using the superlogin Dockerfile
  superlogin:
    env_file:
     - variables.env
    build: ./iihs_curation_auth
    depends_on:
     - couchdb
    ports:
     - "3000:3000"
    # Link the client container so that Nginx will have access to it
    links:
     - couchdb:couchdb
# Build the container using the client Dockerfile
  client:
    build: ./iihs_curation_dashboard
    depends_on:
    - superlogin 
    - couchdb
    - feedparser
    env_file:
     - variables.env
# This line maps the contents of the client folder into the container.
    ports:
     - "80:80"
    links:
     - superlogin:superlogin
     - couchdb:couchdb  
     - feedparser:feedparser

 
  
